In [4]:
!pip install psycopg2-binary
!pip install requests

import pandas as pd
import psycopg2
import requests

Requirement already satisfied: psycopg2-binary in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (2.9.11)
Requirement already satisfied: requests in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from requests) (2026.2.25)

In [15]:
## Andmebaasiga ühendamine
conn = psycopg2.connect(
    host="localhost",
    database="cafe",
    user="postgres",
    password="Parool11"
)
df = pd.read_sql("Select * FROM cafe_sales.cafe_sales_cleaned", conn)
conn.close()
df

C:\Users\opilane\AppData\Local\Temp\ipykernel_10588\2609707597.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("Select * FROM cafe_sales.cafe_sales_cleaned", conn)

,transaction_id,item_cleaned,quantity,unit_price,total_spent_calc,payment_method_cleaned,location_cleaned,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9029,TXN_4766549,Smoothie,2,4.0,8.0,Cash,UNKNOWN,2023-10-20
9030,TXN_7851634,UNKNOWN,4,4.0,16.0,UNKNOWN,UNKNOWN,2023-01-08
9031,TXN_7672686,Coffee,2,2.0,4.0,UNKNOWN,UNKNOWN,2023-08-30
9032,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,UNKNOWN,2023-03-02
9033,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

C:\Users\opilane\AppData\Local\Temp\ipykernel_10588\1465492443.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("Select * FROM cafe_sales.cafe_budget", conn)

   year_month  budget_sum
0     2023-01      6500.0
1     2023-02      6000.0
2     2023-03      6500.0
3     2023-04      6500.0
4     2023-05      6500.0
5     2023-06      7000.0
6     2023-07      7000.0
7     2023-08      7000.0
8     2023-09      7000.0
9     2023-10      6500.0
10    2023-11      6500.0
11    2023-12      7000.0

In [9]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")
response.json()
df = pd.DataFrame(response.json())
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

## Harjutus

In [9]:
def numeric_year(year_string: str) -> int:
    try:
        year_number_str, year_era_notation_str = year_string.split(" ") # tulemuseks list, kuna järjekord on oluline
    except:
        raise ValueError(f"'{year_string}' is not a valid year number: exactly two components expected.")
    
    try:
        year_numeric = int(year_number_str)
    except:
        raise ValueError(f"'{year_string}' is not a valid year number: year not numeric.")
    
    if year_era_notation_str == "A.D.":
        return int(year_number_str)
    if year_era_notation_str == "B.C.":
        return -int(year_number_str)
    else:
        raise ValueError(f"'{year_string}' is not a valid year number: unknown era.")
    

print(numeric_year("2023 A.D."))
print(numeric_year("1993 B.C."))

2023
-1993