# Python, päev 1

Täna õpime Pythoni baasoskuseid.

## *Hello, World!*

In [1]:
print("Hello, World!")

Hello, World!

## Andmetüübid

In [2]:

nimi = "Rainer" # string
PI = 3.14159 # float (kokkulepe: muutuja suurte tähtedega = konstant)
aasta = 2026 # int
sun_rises_from_east = True # bool
years = [2020, 2021, 2022, 2023, 2024] # list
fruits = {"apple", "banana", "cherry"} # set
numbers = (1, 2, 3) # tuple
person = {
    "name": "Alice",
    "age": 30,
    "city": "New York"
} # dict

## Funktsioonid

In [3]:
def greet(description: str, name: str = "Rainer"):
    print("Tere")
    print(nimi) #Function
    print(f"Väga {description} funktsioon, {name}")
print("Ei ole osa funktsioonist, sest on eraldi taandel")

Ei ole osa funktsioonist, sest on eraldi taandel

In [4]:
greet("tore")

Tere
Rainer
Väga tore funktsioon, Rainer

In [5]:
greet("vägev", "Silver")

Tere
Rainer
Väga vägev funktsioon, Silver

In [6]:
def add(a: int, b: int) -> int:
    return a + b

In [7]:
tulemus = add(3, 3)
print(tulemus)

6

## if/else

In [8]:
def make_sense_of_this_year(year: int):
    if year < 0:
        print("B.C")
        if year <= 10000:
            print("Stone Age")
    elif year == 0:
        print("Happy birthday, Jesus")
    else:
        print("A.D")

In [9]:
make_sense_of_this_year(2000)

A.D

In [10]:
def format_year(year: int) -> str:
    if year < 0:
        return f"{abs(year)} B.C"
    else:
        return f"{year} A.D"
print (format_year(2000))

2000 A.D

## For Loop

In [11]:
years = [2021, 2022, 2023, 2024, 2025]
for year in years:
    print(f"Happy {year}")

Happy 2021
Happy 2022
Happy 2023
Happy 2024
Happy 2025

## Pandas

In [17]:
#!pip install pandas

In [13]:
import pandas as pd

In [14]:
data = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [30, 25, 35],
    "city": ["York", "Los", "Chi"]
})
data

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [15]:
data.to_csv("not_very_sensible_data.csv", index=False)

In [16]:
people = pd.read_csv("not_very_sensible_data.csv")
people

  name  age  city
0    A   30  York
1    B   25   Los
2    C   35   Chi

In [19]:
people[["name", "age"]]

  name  age
0    A   30
1    B   25
2    C   35

In [20]:
!pip install duckdb

Collecting duckdb
  Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl.metadata (4.2 kB)
Downloading duckdb-1.5.1-cp314-cp314-win_amd64.whl (13.6 MB)
   ---------------------------------------- 0.0/13.6 MB ? eta -:--:--
   ----- ---------------------------------- 1.8/13.6 MB 10.3 MB/s eta 0:00:02
   -------------------- ------------------- 7.1/13.6 MB 18.5 MB/s eta 0:00:01
   ----------------------------------- ---- 12.1/13.6 MB 20.1 MB/s eta 0:00:01
   ---------------------------------------- 13.6/13.6 MB 19.7 MB/s  0:00:00
Installing collected packages: duckdb
Successfully installed duckdb-1.5.1

In [21]:
import duckdb

In [22]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\users\opilane\appdata\local\programs\python\python314\Lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------ --------------------- 3.7/8.1 MB 19.3 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 22.3 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   ------ --------------------------------- 6.0/37.3 MB 30.5 MB/s eta 0:00:02
   ------------ --------------------------- 11.5/37.3 MB 28.2 MB/s eta 0:00:01
   ----------------- ---------------------- 16.5/37.3 MB 26.0 MB/s eta 0:00:01
   --------------------- ------------------ 20.2/37.3 MB 24.1 MB/s eta 0:00:01
   ---------------------------- ----------- 26.5/37.3 MB 25.1 MB/s eta 0:00:01
   --------------------------------- ------ 31.2/37.3 MB 24.6 MB/s eta 0:00:01
   ---------------------------------------  36.7/37.3 MB 24.8 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 23.4 MB/s  0:00:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   -------------------- ------------------- 2/4 [joblib]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ------------------------------ --------- 3/4 [scikit-learn]
   ---------------------------------------- 4/4 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

In [11]:
from sklearn.datasets import load_iris

In [14]:
iris_data = load_iris()
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target
iris['species'] = iris['target'].map(dict(enumerate(iris_data.target_names)))
iris.pop('target')
iris = iris.rename(columns={
    "sepal length (cm)": "sepal_length",
    "sepal width (cm)": "sepal_width",
    "petal length (cm)": "petal_length",
    "petal width (cm)": "petal_width"
})
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
iris.to_csv("iris.csv", index=False)

In [28]:
duckdb.sql("""
    SELECT 'Hello, World!'
 """)

┌─────────────────┐
│ 'Hello, World!' │
│     varchar     │
├─────────────────┤
│ Hello, World!   │
└─────────────────┘

In [46]:
duckdb.sql("""
    SELECT species, avg(petal_length) AS avg_petal_length
    FROM iris
    GROUP BY species
    ORDER BY avg_petal_length DESC
 """).df()

      species  avg_petal_length
0   virginica             5.552
1  versicolor             4.260
2      setosa             1.462

## Harjutused

In [53]:
def enne_või_pärast_kristust(aasta: int) -> str:
    if aasta < 0:
        return f"{abs(aasta)} B.C."
    elif aasta == 0:
        return "I believe is Jesus is life this morning."
    else:
        return f"{aasta} A.D."
    
enne_või_pärast_kristust(0)

'I believe is Jesus is life this morning.'

In [74]:
inimesed = ['kati', 'mati', 'silveraadomees', 'hannes']
numbrid = ['Esimese', 'Teise', 'Kolmanda', 'Neljanda']

järjekorranumber = 0

for nimi in inimesed:
    nime_pikkus = len(nimi)
    tekst = f"{numbrid[järjekorranumber]} inimese nimi on {nimi.capitalize()} nime pikkusega {nime_pikkus}"
    if nime_pikkus < 5:
        print(f"{tekst} tähte ning ta kannab lühikest nime.")
    else:
        print(f"{tekst} tähte ning ta kannab pikka nime.")
    järjekorranumber += 1

Esimese inimese nimi on Kati nime pikkusega 4 tähte ning ta kannab lühikest nime.
Teise inimese nimi on Mati nime pikkusega 4 tähte ning ta kannab lühikest nime.
Kolmanda inimese nimi on Silveraadomees nime pikkusega 14 tähte ning ta kannab pikka nime.
Neljanda inimese nimi on Hannes nime pikkusega 6 tähte ning ta kannab pikka nime.

## Ülesanne
Vaja leida ostukorvi koguhind.
- Kui toote hind on > 100, siis soodustus 20%
- Kui toote hind on > 50, siis soodustus 10%

In [ ]:
## Raineri variant

hinnad = [120, 45, 89, 200, 33, 75, 150, 10, 99, 101]
soodustus_suur = 0.8
soodustus_vaike = 0.9
uued_hinnad = []

def get_price(hinnad: list[int]) -> float:
    ostukorvi_hind = 0
    for kaup in hinnad:
        if kaup > 100:
            ostukorvi_hind += (kaup * soodustus_suur)
            uued_hinnad.append(round(kaup * soodustus_suur, 2))
        elif kaup > 50:  
            ostukorvi_hind += (kaup * soodustus_vaike) 
            uued_hinnad.append(round(kaup * soodustus_vaike, 2))
        else:
            ostukorvi_hind += kaup
            uued_hinnad.append(round(kaup, 2)) 
    return ostukorvi_hind, uued_hinnad


## Alternatiiv
alternatiiv_ylesanne = """
def get_discount(price: int) -> float:
    if price > 100:
        return price * soodustus_suur
    elif price > 50:
        return price * soodustus_vaike
    return price

def get_price_alternative(hinnad: list[int]) -> float:
    tulemus = 0
    for hind in hinnad:
        soodushind = get_discount(hind)
        tulemus += soodushind
    return tulemus
"""
get_price(hinnad)

(781.5, [96.0, 45, 80.1, 160.0, 33, 67.5, 120.0, 10, 89.1, 80.8])